apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop-dev
  region: us-east-1
  version: "1.34"

managedNodeGroups:
  - name: roboshop-dev
    instanceType: t3.micro
    desiredCapacity: 3
    minSize: 3
    maxSize: 3
    volumeSize: 20