apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: roboshop-dev
    region: us-east-1
nodeGroups:
  - name: roboshop-dev
    instanceType: t3.medium
    desiredCapacity: 2
    capacityType: ON_DEMAND
